name: dl-trader-daily
on:
  workflow_dispatch:
  schedule:
    - cron: '5 17 * * 1-5'
permissions:
concurrency:
  group: dl-trader-daily
  cancel-in-progress: false
  contents: write
jobs:
  train:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin
      SYMBOLS: SPY,QQQ
      START_DATE: 2015-01-01
      DATA_DIR: data
      POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Abhängigkeiten
        run: pip install -r backend/app/requirements.txt
      - name: Pipeline ausführen
        run: |
          python - <<'PY'
          import pathlib, sys, json
          repo = pathlib.Path().resolve()
          sys.path.insert(0, str(repo/'backend'/'app'))
          from app.tasks_inline import run_daily
          rows, errs = run_daily()
          print("rows:", rows)
          print("errors:", errs)
          PY
      - name: Ergebnisse committen
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/signals.json docs/state.json data/signals.csv || true
          git commit -m "daily signals (DL)" || echo "nichts zu committen"
          git push
