name: daily-train-and-publish

on:
  workflow_dispatch:
  schedule:
    - cron: "10 16 * * 1-5"  # 16:10 UTC ~ 17:10/18:10 Europe/Berlin (je nach DST)

permissions:
  contents: write

concurrency:
  group: daily-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Run training & build public
        env:
          SYMBOLS: ${{ vars.SYMBOLS || 'SPY,QQQ' }}
          START_DATE: ${{ vars.START_DATE || '2015-01-01' }}
          CAMPAIGN_DAYS: 60
          REPO_SLUG: ${{ github.repository }}
        run: |
          python scripts/ci_daily.py
          test -f public/index.html
          test -f public/data/signals.json

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: true
