name: Train and Publish

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # stündlich

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (CPU Torch)
        run: |
          python -m pip install --upgrade pip
          pip install --index-url https://download.pytorch.org/whl/cpu torch==2.3.1
          pip install pandas numpy yfinance

      - name: Run training
        env:
          SYMBOLS: "SPY,QQQ,TLT,GLD"
          HISTORY_YEARS: "5"
          EPOCHS: "8"
        run: python scripts/train_and_publish.py

      - name: Commit and push changes (if any)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add docs/data/*
            git commit -m "CI: update signals & metrics [skip ci]"
            git push origin HEAD:main
          fi
